version: "3.9"

services:
  db:
    image: postgres:15
    container_name: backend_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: backend_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    build: .
    container_name: backend_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - backend_network
    command: npm run dev

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
